export const CREATE_EVENT="CREATE_EVENT"


export const FETCH_EVENTS="FETCH_EVENTS"




export const FETCH_ALL_EVENTS="FETCH_ALL_EVENTS"



export const FETCH_NEARBY="FETCH_NEARBY"


export const USER_FETCH_RANDOM_EVENTS="USER_FETCH_RANDOM_EVENTS"